name: Build Executables

on:
  push:
    branches:
      - "test-github-actions"
  workflow_dispatch:

jobs:
  publish-docker:
    name: Publish Docker images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64,arm

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=${{ secrets.DOCKER_USER }}/ts3-manager
          TAGS="${DOCKER_IMAGE}:latest"

          # If event is release, add release version tag
          if [[ $GITHUB_EVENT_NAME == release ]]; then
            TAGS="$TAGS,${DOCKER_IMAGE}:${{ github.event.release.tag_name }}"
          fi

          # Set output parameters.
          echo ::set-output name=tags::${TAGS}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7
          push: true
          tags: ${{ steps.prep.outputs.tags }}
